version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Amsterdam"
      - "LOG_LEVEL=debug"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 0 4 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_GOTIFY_ENDPOINT=https://notifications.makstra.nl"
      - "DIUN_NOTIF_GOTIFY_TOKEN=AoIUcofpp_f7yra"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: unless-stopped